topicName = "Irregular verbs";
cards = [
{"tgt":"dar",
 "ntv":"to give",
 "forms":[["yo","doy", "I"],
          ["tú","das", "You"],
          ["él","da", "He"],
          ["ella","da", "She"],
          ["usted","da", "You (formal)"],
          ["nosotros","damos", "We (musculine)"],
          ["nosotras","damos", "We (feminine)"],
          ["vosotros","dais", "You (plural, masculine)"],
          ["vosotras","dais", "You (plural, feminine)"],
          ["ellos","dan", "They (masculine)"],
          ["ellas","dan", "They (feminine)"],
          ["ustedes","dan", "You (plural, formal)"]]
},
{"tgt":"decir",
 "ntv":"to say",
 "forms":[["yo","digo", "I"],
          ["tú","dices", "You"],
          ["él","dice",  "He"],
          ["ella","dice", "She"],
          ["usted","dice", "You (formal)"],
          ["nosotros","decimos", "We (musculine)"],
          ["nosotras","decimos", "We (feminine)"],
          ["vosotros","decís", "You (plural, masculine)"],
          ["vosotras","decís", "You (plural, feminine)"],
          ["ellos","dicen", "They (masculine)"],
          ["ellas","dicen", "They (feminine)"],
          ["ustedes","dicen", "You (plural, formal)"]]
},
{"tgt":"estar",
 "ntv":"to be (temp)",
 "forms":[["yo","estoy"],
          ["tú","estás", "You"],
          ["él","está", "He"],
          ["ella","está", "She"],
          ["usted","está", "You (formal)"],
          ["nosotros","estámos", "We (musculine)"],
          ["nosotras","estámos", "We (feminine)"],
          ["vosotros","estáis", "You (plural, masculine)"],
          ["vosotras","estáis", "You (plural, feminine)"],
          ["ellos","están", "They (masculine)"],
          ["ellas","están", "They (feminine)"],
          ["ustedes","están", "You (plural, formal)"]]
},
{"tgt":"ir",
 "ntv":"to go",
 "forms":[["yo","voy", "I"],
          ["tú","vas", "You"],
          ["él","va", "He"],
          ["ella","va", "She"],
          ["usted","va", "You (formal)"],
          ["nosotros","vamos", "We (musculine)"],
          ["nosotras","vamos", "We (feminine)"],
          ["vosotros","vais", "You (plural, masculine)"],
          ["vosotras","vais", "You (plural, feminine)"],
          ["ellos","van", "They (masculine)"],
          ["ellas","van", "They (feminine)"],
          ["ustedes","van", "You (plural, formal)"]]
},
{"tgt":"oir",
 "ntv":"to hear",
 "forms":[["yo","oigo", "I"],
          ["tú","oyes", "You"],
          ["él","oye", "He"],
          ["ella","oye", "She"],
          ["usted","oye", "You (formal)"],
          ["nosotros","oímos", "We (musculine)"],
          ["nosotras","oímos", "We (feminine)"],
          ["vosotros","oís", "You (plural, masculine)"],
          ["vosotras","oís", "You (plural, feminine)"],
          ["ellos","oyen", "They (masculine)"],
          ["ellas","oyen", "They (feminine)"],
          ["ustedes","oyen", "You (plural, formal)"]]
},
{"tgt":"ser",
 "ntv":"to be (constant)",
 "forms":[["yo","soy", "I"],
          ["tú","eres", "You"],
          ["él","es", "He"],
          ["ella","es", "She"],
          ["usted","es", "You (formal)"],
          ["nosotros","somos", "We (musculine)"],
          ["nosotras","somos", "We (feminine)"],
          ["vosotros","sois", "You (plural, masculine)"],
          ["vosotras","sois", "You (plural, feminine)"],
          ["ellos","son", "They (masculine)"],
          ["ellas","son", "They (feminine)"],
          ["ustedes","son", "You (plural, formal)"]]
},
{"tgt":"tener",
 "ntv":"to have",
 "forms":[["yo","tengo", "I"],
          ["tú","tienes", "You"],
          ["él","tiene", "He"],
          ["ella","tiene", "She"],
          ["usted","tiene", "You (formal)"],
          ["nosotros","tenemos", "We (musculine)"],
          ["nosotras","tenemos", "We (feminine)"],
          ["vosotros","tenéis", "You (plural, masculine)"],
          ["vosotras","tenéis", "You (plural, feminine)"],
          ["ellos","tienen", "They (masculine)"],
          ["ellas","tienen", "They (feminine)"],
          ["ustedes","tienen", "You (plural, formal)"]]
},
{"tgt":"venir",
 "ntv":"to come",
 "forms":[["yo","vengo", "I"],
          ["tú","vienes", "You"],
          ["él","viene", "He"],
          ["ella","viene", "She"],
          ["usted","viene", "You (formal)"],
          ["nosotros","venimos", "We (musculine)"],
          ["nosotras","venimos", "We (feminine)"],
          ["vosotros","venís", "You (plural, masculine)"],
          ["vosotras","venís", "You (plural, feminine)"],
          ["ellos","vienen", "They (masculine)"],
          ["ellas","vienen", "They (feminine)"],
          ["ustedes","vienen", "You (plural, formal)"]]
}
];
