deckName = "Big";
cards = [
{"sp":"poder (o->ue)",
 "en": "can/might",
 "sp_ex": ["yo puedo ver te"],
 "en_ex": ["I can see you"],
 "ctable": [["p<r>ue</r>do","p<r>ue</r>des","p<r>ue</r>de","podemos","podéis","p<r>ue</r>den"]],
 "img":"decks/big_imgs/poder.jpg"},
{"sp":"saber",
 "en": "to know (information)",
 "sp_ex": ["yo lo sé"],
 "en_ex": ["I know it"],
 "ctable": [["s<r>é</r>","sabes","sabe","sabemos","sabéis","saben"]],
 "img":"decks/big_imgs/saber.png"},
{"sp":"conocer",
 "en": "to know (person or place)",
 "sp_ex": ["¿Qué tanto conozco a mi hijo?", "yo conozco Madrid"],
 "en_ex": ["How good I know my son?", "I know Madrid"],
 "ctable": [["cono<r>z</r>co","conoces","conoce","conocemos","comocéis","comocen"]],
 "img":"decks/big_imgs/conocer.png"},
{"sp":"ser",
 "en": "to be",
 "sp_ex": ["Yo soy ingeniero informático. ¿Cuál es tu superpoder?"],
 "en_ex": ["I am a software engineer. What is your superpower?"],
 "ctable": [["<r>soy</r>","<r>eres</r>","<r>es</r>","<r>somos</r>","<r>sois<r>","<r>son</r>"]],
 "img":"decks/big_imgs/ingeniero.jpg"},
{"sp":"estar",
 "en": "to be",
 "sp_ex": ["Yo estoy así así / más o menos. ¿Y tú?","Yo estoy bien/mal/regular. ¿Y tú?", "Yo estoy aqui", "Yo estoy feliz"],
 "en_ex": ["I am so-so / more or less/okay. And you?", "I am fine/bad/okay. And you?", "I am here", "I am happy"],
 "ctable": [["est<r>oy</r>","est<r>á</r>s","est<r>á</r>","estamos","est<r>á</r>is","est<r>á</r>n"]],
 "img":"decks/big_imgs/aqui.jpg"},
{"sp":"el invierno",
 "en": "the winter",
 "sp_ex": ["El invierno pasado yo fui un asesino"],
 "en_ex": ["In the last winter I was an assassin"],
 "ctable": [],
 "img":"decks/big_imgs/winter.jpg"},
{"sp":"el profesor/la profesora",
 "en": "the professor",
 "sp_ex": ["Yo soy profesora. ¿Cuál es tu superpoder?"],
 "en_ex": ["I am a professor(f). What is your superpower?"],
 "ctable": [],
 "img":"decks/big_imgs/profesora.jpg"},
{"sp":"ir",
 "en": "to go",
 "sp_ex": ["yo voy contigo a la playa", "tu vas conmigo al parque", "nosotros vamos a pie", "vamos el cine"],
 "en_ex": ["I am going to the beach with you", "you are going to the park with me", "we are going to walk", "we are going to the cinema"],
 "ctable": [["<r>voy</r>","<r>vas</r>","<r>va</r>","<r>vamos</r>","<r>vais</r>","<r>van</r>"]],
 "img":"decks/big_imgs/ir.jpg"},
]



