deckName = "Big";
cards = [
{"sp":"poder (o->ue)",
 "en": "can/might",
 "sp_ex": ["yo puedo verte"],
 "en_ex": ["I can see you"],
 "ctable": [["p<r>ue</r>do","p<r>ue</r>des","p<r>ue</r>de","podemos","podéis","p<r>ue</r>den"]],
 "img":"decks/big_imgs/poder.jpg"},
{"sp":"saber",
 "en": "to know (information)",
 "sp_ex": ["yo lo sé"],
 "en_ex": ["I know it"],
 "ctable": [["s<r>é</r>","sabes","sabe","sabemos","sabéis","saben"]],
 "img":"decks/big_imgs/saber.png"},
{"sp":"conocer",
 "en": "to know (person or place)",
 "sp_ex": ["¿Qué tanto conozco a mi hijo?", "yo conozco Madrid"],
 "en_ex": ["How good I know my son?", "I know Madrid"],
 "ctable": [["cono<r>z</r>co","conoces","conoce","conocemos","comocéis","comocen"]],
 "img":"decks/big_imgs/conocer.png"},
{"sp":"ser",
 "en": "to be",
 "sp_ex": ["Yo soy ingeniero informático. ¿Cuál es tu superpoder?"],
 "en_ex": ["I am a software engineer. What is your superpower?"],
 "ctable": [["<r>soy</r>","<r>eres</r>","<r>es</r>","<r>somos</r>","<r>sois<r>","<r>son</r>"]],
 "img":"decks/big_imgs/ingeniero.jpg"},
{"sp":"estar",
 "en": "to be",
 "sp_ex": ["Yo estoy así así / más o menos. ¿Y tú?","Yo estoy bien/mal/regular. ¿Y tú?", "Yo estoy aqui", "Yo estoy feliz"],
 "en_ex": ["I am so-so / more or less/okay. And you?", "I am fine/bad/okay. And you?", "I am here", "I am happy"],
 "ctable": [["est<r>oy</r>","est<r>á</r>s","est<r>á</r>","estamos","est<r>á</r>is","est<r>á</r>n"]],
 "img":"decks/big_imgs/aqui.jpg"},
{"sp":"el invierno",
 "en": "the winter",
 "sp_ex": ["El invierno pasado yo fui un asesino"],
 "en_ex": ["The last winter I was an assassin"],
 "ctable": [],
 "img":"decks/big_imgs/winter.jpg"},
{"sp":"el profesor/la profesora",
 "en": "the professor",
 "sp_ex": ["Yo soy profesora. ¿Cuál es tu superpoder?"],
 "en_ex": ["I am a professor(f). What is your superpower?"],
 "ctable": [],
 "img":"decks/big_imgs/profesora.jpg"},
{"sp":"ir",
 "en": "to go",
 "sp_ex": ["yo voy contigo a la playa", "tu vas conmigo al parque", "nosotros vamos a pie", "vamos al cine"],
 "en_ex": ["I am going to the beach with you", "you are going to the park with me", "we are going to walk", "we are going to the cinema"],
 "ctable": [["<r>voy</r>","<r>vas</r>","<r>va</r>","<r>vamos</r>","<r>vais</r>","<r>van</r>"]],
 "img":"decks/big_imgs/ir.jpg"},
{"sp":"decir",
 "en": "to speak",
 "sp_ex": ["yo digo la verdad","Le digo mi opinio'n"],
 "en_ex": ["I am telling the truth", "I am telling you all my opinion"],
 "ctable": [["<r>digo</r>","<r>dices</r>","<r>dice</r>","<r>decimos</r>","<r>decís</r>","<r>dicen</r>"]],
 "img":""},
{"sp":"¿Qué tal?",
 "en": "How are you",
 "sp_ex": ["¿Qué tal?"],
 "en_ex": ["How are you?"],
 "ctable": [],
 "img":""},
{"sp":"¿Cómo Estás?",
 "en": "How are you",
 "sp_ex": ["¿Cómo Estás?"],
 "en_ex": ["How are you?"],
 "ctable": [],
 "img":""},
{"sp":"hablar",
 "en": "to speak",
 "sp_ex": ["¿Hablas español? Sí", "Ella habla ingles um poco", "¿Hay alguien que hable español?", "¿Alguno de ustedes habla español?"],
 "en_ex": ["Do you speak Spanish? Yes", "She speaks English a bit", "Do we have anyone who can speak Spanish?","Either one of you guys speak Spanish?"],
 "ctable": [["hablo","hablas","habla","hablamos","habláis","hablan"]],
 "img":""},
{"sp":"comer",
 "en": "to eat",
 "sp_ex": ["Yo como pollo aunque no como pescado"],
 "en_ex": ["I eat chicken though I don't eat fish"],
 "ctable": [["como","comes","come","comemos","coméis","comen"]],
 "img":""},
{"sp":"vivir",
 "en": "to live",
 "sp_ex": ["Tú vas a vivir en una casa bonita"],
 "en_ex": ["You are going to live in a pretty house"],
 "ctable": [["vivo","vives","vive","vivimos","viveís","viven"]],
 "img":""},
{"sp":"buscar",
 "en": "to find",
 "sp_ex": ["Al menos sabemos a quién buscar"],
 "en_ex": ["At least we know whom to find"],
 "ctable": [["busco","buscas","busca","buscamos","buscáis","buscan"]],
 "img":""},
{"sp":"haber",
 "en": "to have (to do smth, aux verb)",
 "sp_ex": ["ya había tenido suficiente"],
 "en_ex": ["I already have enough(I am tired)"],
 "ctable": [["he","has","ha/hay","hemos","habéis","han"]],
 "img":""},
{"sp":"tener (e->ie)",
 "en": "to have",
 "sp_ex": ["Yo tengo oche computadoras"],
 "en_ex": ["I haveeat chicken though I don't eat fish"],
 "ctable": [["ten<r>g</r>o","t<r>ie</r>nes","t<r>ie</r>ne","tenemos","tenéis","t<r>ie</r>nen"]],
 "img":""},
{"sp":"hacer",
 "en": "to do, to make",
 "sp_ex": ["Yo Hago Lo Que Quiera"],
 "en_ex": ["I do what I want"],
 "ctable": [["ha<r>go</r>","haces","hace","hacemos","hacéis","hacen"]],
 "img":""},
{"sp":"ver",
 "en": "to see",
 "sp_ex": ["Yo veo tu cara"],
 "en_ex": ["I see your face"],
 "ctable": [["v<r>eo</r>","ves","ve","vemos","<r>veis</r>","ven"]],
 "img":""},
{"sp":"dar",
 "en": "to give",
 "sp_ex": ["Emiliano, le doy mi palabra"],
 "en_ex": ["Emilian, I give you my word"],
 "ctable": [["<r>doy</r>","das","de","damos","<r>dais</r>","dan"]],
 "img":""},
{"sp":"querer (e-ie)",
 "en": "to like smth, to love smb",
 "sp_ex": ["Yo quiero una camisa negra"],
 "en_ex": ["I wanna a black shirt"],
 "ctable": [["qu<r>ie</r>ro","qu<r>ie</r>res","qu<r>ie</r>re","queremos","queréis","qu<r>ie</r>ren"]],
 "img":""},
{"sp":"llegar",
 "en": "to arrive,come,reach",
 "sp_ex": ["Y él llega tarde"],
 "en_ex": ["And he is [arriving] late"],
 "ctable": [["llego","llegas","llega","llegamos","llegáis","llegan"]],
 "img":""},
{"sp":"pasar",
 "en": "to pas, to spend (time), to happen",
 "sp_ex": ["Yo paso tiempo libre con ella"],
 "en_ex": ["I spend free time with her"],
 "ctable": [["paso","pasas","pasa","pasamos","pasáis","pasan"]],
 "img":""},
{"sp":"deber",
 "en": "to owe, must, should, ought to",
 "sp_ex": ["Tú puedes faltar, pero yo debo ir"],
 "en_ex": ["You can skip, but I need to go"],
 "ctable": [["debo","debes","debe","debemos","debéis","deben"]],
 "img":""},
{"sp":"poner (irr)",
 "en": "to put, place, set",
 "sp_ex": ["Acá abajo, yo pongo las reglas", "Yo pongo más dinero aquí que cualquier otro, ok, - así que chiton"],
 "en_ex": ["Down here, I set the rules", "I put more money there than any other, ok - so shut up"],
 "ctable": [["<r>pengo</r>","pones","pone","ponemos","ponéis","ponen"]],
 "img":""},
{"sp":"parecer (irr)",
 "en": "to seem, appear",
 "sp_ex": ["Bueno, estoy seguro de que parezco cansado", "Que estas diciendo, te parezco cansado?"],
 "en_ex": ["Okay, I know that I look tired", "Do you think I look tired?"],
 "ctable": [["<r>parezco</r>","pareces","parece","parecemos","paracéis","paracen"]],
 "img":""},
{"sp":"quedar",
 "en": "to stay, remain",
 "sp_ex": ["Sí, lo que queda de él"],
 "en_ex": ["Yes, this what is remain from him"],
 "ctable": [["quedo","quedas","queda","quedamos","quedáis","quedan"]],
 "img":""},
{"sp":"creer",
 "en": "to believe",
 "sp_ex": ["De veras yo no creo que tu puedas"],
 "en_ex": ["Really, I don't think you can"],
 "ctable": [["creo","crees","cree","creemos","creéis","creen"]],
 "img":""},
]



